apiVersion: v1
kind: Service
metadata:
  name: springboot-kubs-app
spec:
  selector:
    app: springboot-kubs-app
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort